# Generated by Django 3.1.3 on 2022-12-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
    ]
