# Generated by Django 3.1.3 on 2023-02-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20230202_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='url_icon',
            new_name='affiliate_url',
        ),
    ]
