# Generated by Django 3.1.3 on 2023-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20230202_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='affiliate_url',
            new_name='affiliate',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='video',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
    ]
