# Generated by Django 3.1.3 on 2022-12-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
