# Generated by Django 3.1.3 on 2022-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
