# Generated by Django 3.1.3 on 2023-02-02 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0005_auto_20230202_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_favorite',
            field=models.ManyToManyField(blank=True, related_name='category_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
