# Generated by Django 3.1.3 on 2022-12-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_bookmark_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
