# Generated by Django 3.1.3 on 2023-02-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20230203_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='video',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_favorite',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
