# Generated by Django 3.1.3 on 2022-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_bookmark_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='visits',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
