# Generated by Django 3.1.3 on 2022-12-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0009_auto_20221227_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='visits',
        ),
    ]
