# Generated by Django 3.1.3 on 2023-01-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_remove_bookmark_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='video',
        ),
    ]
