# Generated by Django 3.1.3 on 2023-01-04 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0011_remove_bookmark_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='url_icon',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
