# Generated by Django 3.1.3 on 2023-01-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0012_bookmark_url_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url_icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
