# Generated by Django 3.1.3 on 2023-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0013_auto_20230104_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='body',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
    ]
