# Generated by Django 3.1.3 on 2023-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0016_auto_20230124_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
