# Generated by Django 3.1.3 on 2023-01-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0017_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
