# Generated by Django 3.1.3 on 2023-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('follower', 'Follower'), ('vote', 'Vote'), ('mention', 'Mention')], max_length=20),
        ),
    ]
